cart/urls.py
from . import views
from django.urls import path
app_name='cart'
urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('remove/<slug:product_slug>/', views.cart_remove, name="cart_remove"),
    path('add/<slug:product_slug>/', views.cart_add, name="cart_add"),
    

]

orders/urls.py
from . import views
from django.urls import path
app_name='orders'
urlpatterns = [
    path('create/',views.order_create,name="order_create"),
    path('pay_order/<int:order_id>/', views.order_pay_by_vodafon, name="order_pay_by_vodafon"),
    path('payment_success/<int:order_id>/', views.payment_success, name="payment_success"),
    # path('admin/pdf/<int:order_id>/', views.admin_order_id, name="admin_order_id"),


]


project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls',namespace='store')),

    path('accounts/', include('accounts.urls',namespace='accounts')),    
    path('cart/', include('cart.urls',namespace='cart')),   
    path('orders/', include('orders.urls',namespace='orders')),    
 



    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES=[(i,str(i)) for i in range(1,51)]

# class CartAddProductForm(forms.Form):
#     quantity=forms.TypedChoiceField( choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
#     override=forms.BooleanField(initial=False, required=False,widget=forms.HiddenInput)
    
# class CartAddProductForm(forms.Form):
#     quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, initial=1)  # Set default quantity to 1
#     override = forms.BooleanField(initial=False, required=False, widget=forms.HiddenInput)
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int )  # Set default quantity to 1  ,initial=1
    override = forms.BooleanField(initial=False, required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django .views.decorators.http import require_POST

      
@require_POST
def cart_add(request, product_slug):
    cart = Cart(request)
    product = get_object_or_404(Product, slug=product_slug, status=Product.Status.AVAILABLE)
    form = CartAddProductForm(request.POST)
    
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])

        return redirect('cart:cart_detail')
    else:
        return redirect('store:products_detail', product_slug=product.slug)


@require_POST
def cart_remove(request,product_slug) ->int:
    cart=Cart(request)
    product=get_object_or_404(Product,slug=product_slug,status=Product.Status.AVAILABLE)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart=Cart(request)
    cart_product_form=CartAddProductForm() 
    for item in cart:
        item['update_quantity_form']=CartAddProductForm(initial={
           'quantity':item['quantity'],
           'override':True 
        })
    context={
        'cart':cart,
        'cart_product_form':cart_product_form
    }
    return render(request,'cart_details.html',context)

cart/templates/cart_details.html
{% extends "base.html" %}

{% block body %}


    <!-- cart section -->
    <section class="cart_section layout_padding">
        <div class="container">
            <div class="heading_container heading_center">
                <h2>
                    Shopping Cart
                </h2><br><br>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="cart_items">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Product</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Total</th>
                                    <th scope="col">remove</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                {% comment %} {% with product=item.product %} {% endcomment %}
                              
                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <img src="{{item.product.image.url}}" alt="Product Name" class="img-fluid" style="width: 50px; height: 50px; object-fit: cover; margin-right: 10px;">
                                            {{item.product.name}}
                                        </div>
                                    </td>
                                    <td>${{item.product.price}}</td>
                                    <td>
                                        <form action="{% url 'cart:cart_add' item.product.slug  %}" method="POST">
                                            {% csrf_token %}

                                            {{item.update_quantity_form.quantity}}
                                            {{item.update_quantity_form.override}}

                                            <input type="submit" value="update" class="btn btn-warning"></form>
                                    </td>
                                    <td>${{item.total_price}}</td>
                                    <td><form action="{% url 'cart:cart_remove' item.product.slug  %}" method="POST">
                                                    {% csrf_token %}
                                                    <input type="submit" value="remove" class="btn btn-danger"></form>
                                    </td>
                                </tr>
                                <!-- Repeat for more items -->
                                {% comment %} {% endwith %} {% endcomment %}
                                {% endfor %}
                            </tbody>
                 
                        </table>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart_summary">
                        <h4>Cart Summary</h4>
                        <ul>
                            <li>Subtotal: <span>$300</span></li>
                            <li>Tax: <span>$30</span></li>
                            <li>Total: <span>${{cart.get_total_price}}</span></li>
                        </ul>
                        <form class="coupon_form mt-4">
                            <label for="coupon_code">Coupon Code</label>
                            <input type="text" id="coupon_code" class="form-control" placeholder="Enter your code">
                            <button type="submit" class="btn btn-primary mt-2">Apply Coupon</button>
                        </form>
                        <a href="{% url 'orders:order_create' %}" class="btn btn-success mt-4 w-100"> Checkout </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end cart section -->

{% endblock body %}