accounts/urls.py
from . import views
from django.urls import path
app_name='accounts'
urlpatterns = [
    path('register',views.register,name="register"),
    path('login/',views.login,name="login"),
    path('activate/<uidb64>/<token>/',views.activate,name="activate"),

]

cart/urls.py
from . import views
from django.urls import path
app_name='cart'
urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('remove/<slug:product_slug>/', views.cart_remove, name="cart_remove"),
    path('add/<slug:product_slug>/', views.cart_add, name="cart_add"),
    

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls',namespace='store')),

    path('accounts/', include('accounts.urls',namespace='accounts')),    
    path('cart/', include('cart.urls',namespace='cart')),   
    path('orders/', include('orders.urls',namespace='orders')),    
 



    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from . import views
from django.urls import path
app_name='store'
urlpatterns = [
    path('',views.list_products,name="home"),
    path('category/<slug:slug>/',views.list_products,name="category_detail"),

    path('product/<slug:product_slug>/',views.products_detail,name="products_detail"),

    path('search/',views.product_search,name="product_search"),


]

templates/parts/alerts.html
<div class="message-container text-center">
    {% if messages %}
        {% for message in messages %}
            <div id="message" class="x">
                <div {% if message.tags %}class="alert alert-{{ message.tags }}"{% endif %} role="alert">
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
                    <h5><b>{{ message }}</b></h5>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js">
</script>
<script>

    $(document).ready(function(){
        setTimeout(function(){
            $('.x').fadeOut('slow');
        }, 3000);
    });
</script>

templates/parts/footer.html
{% load static %}
<section class="info_section ">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_contact">
            <h5>
              <a href="" class="navbar-brand">
                <span>
                  Minics
                </span>
              </a>
            </h5>
            <p>
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              Address
            </p>
            <p>
              <i class="fa fa-phone" aria-hidden="true"></i>
              +20 01015651362
            </p>
            <p>
              <i class="fa fa-envelope" aria-hidden="true"></i>
              ameer.waeel99@gmail.com
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_info">
            <h5>
              Information
            </h5>
            <p>
              This site was built in Python, Django Back and HTML, CSS, JavaScript Front and Back, and PostgreSQL Database. It is an e-commerce site for trading and selling all products.            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_links">
            <h5>
              Useful Link
            </h5>
            <ul>
              <li>
                <a href="{% url 'store:home'%}">
                  Home
                </a>
              </li>
              <li>
                <a href="about.html">
                  About
                </a>
              </li>
              <li>
                <a href="{% url 'store:home'%}">
                  Products
                </a>
              </li>
              <li>
                <a href="why.html">
                  Why Us
                </a>
              </li>
              <li>
                <a href="testimonial.html">
                  Testimonial
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_form ">
            <h5>
              Newsletter
            </h5>
            <form action="">
              <input type="email" placeholder="Enter your email">
              <button>
                Subscribe
              </button>
            </form>
            <div class="social_box">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-youtube" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/parts/header.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- header section strats -->
    <header class="header_section">
      <div class="header_top">
        <div class="container-fluid">
          <div class="top_nav_container">
            <div class="contact_nav">
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call : +20 01015651362
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  Email : ameer.waeel99@gmail.com
                </span>
              </a>
            </div>

            <form class="search_form" method="get" action="{% url 'store:product_search' %}">
              <input type="text" name="query" class="form-control" placeholder="Search here...">
              <button type="submit">
                  <i class="fa fa-search" aria-hidden="true"></i>
              </button>
          </form>
          


            <div class="user_option_box">
              <a href="{% url 'accounts:register'%}" class="account-link">
                <i class="fa fa-user" aria-hidden="true"></i>
                <span>
                  My Account
                </span>
              </a>
              <a href="{% url 'cart:cart_detail'%}" class="account-link">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                <span>
                  Cart
                </span>
                {% comment %} {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    <small> 
                        <a href="{% url 'cart:cart_detail'%}">
                          items is ( {{ total_items }} )  
                           {{ cart.get_total_price }} $
                        </a>
                    </small>
                {% endif %}
            {% endwith %}
             {% endcomment %}
             {% with total_items=cart|length %}
    {% if total_items > 0 %}
        <small>
            <a href="{% url 'cart:cart_detail' %}">
              Items : {{ total_items }}  |  
                {% comment %} Total: {{ cart.get_total_price|default_if_none:"0.00" }} $ {% endcomment %}
                $ {{ cart.get_total_price }} 

            </a>
        </small>
    {% endif %}
{% endwith %}

              </a>
            </div>
          </div>

        </div>
      </div>
      <div class="header_bottom">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="{% url 'store:home'%}">
              <span>
                E-commerce
              </span>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""> </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'store:home'%}">Home</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for x in categories  %}
                          <a class="dropdown-item" href="{{x.get_category_url}}">{{x.name}}</a>
                    {% endfor %}
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      {% comment %} {% for x in categories  %}
                            <a class="dropdown-item" href="{% url 'store:category_detail' x.slug %}">{{x.name}}</a>
                      {% endfor %} {% endcomment %}
                    
                  </div>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="about.html"> About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'store:home'%}">Products</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="why.html">Why Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="testimonial.html">Testimonial</a>
                </li>
              
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </header>
    <!-- end header section -->
